config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'welcome/index'

  resources :books
  resources :users
  resources :sessions

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, :author, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :books

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # before_action do
  #   @current_user = User.find(session[:id])
  # end

  def authenticate_user!
    unless user_signed_in
      redirect_to new_session_path
    end
  end

  def user_signed_in?
    @current_user.present?
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session [:user_id]
  end
  helper_method :current_user

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :description, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    @session = Session.find(params[:id])
  end

  def show
    @session = @current_user.present?
  end

  def new
    @session != @current_user.present?
  end

  def create
    username = params[:user][:username]
    user_password = params[:user][:password_digest]
    user = User.find_by_username(username)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to new_user_path
    end
  end

  def destroy
    reset_session
    redirect_to root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
  end

  def show
    @user = @current_user.find(params[:user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user_id
      redirect_to :home, notice: 'Account created successfully'
    else
      flash[:error] = 'An error occurred!'
      render 'new'
    end
  end

private

  def authenticate_user!
    unless user_signed_in?
      redirect_to new_session_path
    end
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :URL%><br />
    <%= f.text_field :url%>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/books/edit.html.erb
<h1>Edit this book:</h1>

<%= render 'form' %>
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Look at Our Books!</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Description</th>
    <th>URL</th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.description %></td>
      <td><%= book.url %></td>

      <td><%= link_to 'Show', book_path(book) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book_path(book),
              method: :delete,
              data: { confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>

</table>
<br />
<p>
  <%= link_to 'Home', root_path %> |
  <%= link_to 'New book', new_book_path %> |
  <%= link_to 'Login', new_session_path %>
</p>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>URL:</strong>
  <%= @book.url %>
</p>

<p>
  <%= link_to 'Edit', edit_book_path(@book) %> |
  <%= link_to 'Back', books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freeshelf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<h1>Sign Up</h1>
<%= form_for :user, url: '/users/new' do |f| %>
<p>
  <%= f.label :username %><br />
  <%= f.text_field :username %>
</p>

<p>
  <%= f.label :email %><br />
  <%= f.text_field :email%>
</p>

<p>
  <%= f.label :password %><br />
  <%= f.password_field :password_digest %>
</p>

<p>
  <%= f.label :passord_confirmation %><br />
  <%= f.password_field :password_confirmation %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/users/new.html.erb
<h1>Sign In</h1>
<%= form_for :user, url: 'users/new' do |f| %>
<p>
  <%= f.label :username %><br />
  <%= f.text_field :username %>
</p>

<p>
  <%= f.label :email %><br />
  <%= f.text_field :email%>
</p>

<p>
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</p>

<p>
  <%= f.label :passord_confirmation %><br />
  <%= f.password_field :password_confirmation %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

<% if @user.errors.any? %>
<ul class="Signup_Errors">
  <% for message_error in @user.errors.full_messages %>
  <li>* <%= message_error %></li>
  <% end %>
</ul>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Freeshelf!</h1>

<p>
  <%= link_to 'Check Out Our Books', controller: 'books' %> |
  <%= link_to 'Login', new_session_path %>
</p>